"""Phase-0 trust gate for job apply URLs.

This module is the ONLY place that decides whether a job's apply URL
is safe to surface in the UI. All callers must go through
``resolve_trusted_apply_url``; nothing else may construct an apply URL.

Trust chain (all checks are AND-gated):
    1. The URL must be a non-empty string that passes basic scheme validation.
    2. The URL must NOT match known placeholder patterns (jk=abc123, etc.).
    3. The URL must NOT have been produced by LLM output (origin != 'llm').
    4. The job record must carry at least ONE of the trusted provenance fields:
           - persisted_job_id   set by the DB write path, never by LLM
           - source_job_id      set by provider / scraper ingestion
           - provider + source_backed == True   set by ingestion layer
       plain ``job_id`` alone does NOT satisfy condition 4.

If the URL fails any condition, ``resolve_trusted_apply_url`` returns
``None`` and the caller must show the no-apply-link safe message instead
of a "View & Apply" button.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Optional

from src.services.source_quality import is_placeholder_url

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Internal constants
# ---------------------------------------------------------------------------

# URL schemes accepted as apply links.
_ALLOWED_SCHEMES: frozenset[str] = frozenset({"https", "http"})

# Regex that matches sequential / obviously-generated LinkedIn job IDs.
# LinkedIn real IDs are long (10+ digits) and not sequentially patterned
# from LLM outputs (1, 2, 3 … or 100, 200, 300 …).
_SEQUENTIAL_LINKEDIN_JOB_ID_RE = re.compile(
    r"linkedin\.com/jobs/view/(?P<id>\d{1,6})(?:/|$|\?)",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def resolve_trusted_apply_url(
    job: dict[str, Any],
    *,
    url_field: str = "external_url",
    origin: Optional[str] = None,
) -> Optional[str]:
    """Return the apply URL if and only if it is source-backed and non-fake.

    Parameters
    ----------
    job:
        The job dict as stored / returned by the backend.  Must be a DB
        record or an ingestion-layer object — never raw LLM output.
    url_field:
        The key that holds the apply URL inside *job*.  Defaults to
        ``external_url``.  ``alt_url`` and ``source_url`` are also
        accepted field names for callers that store URLs differently.
    origin:
        Optional hint about where *job* came from.  Pass ``'llm'`` when
        the dict was synthesised by the language model so the guard can
        reject it immediately without inspecting individual fields.

    Returns
    -------
    str | None
        The verified URL string, or ``None`` if the job has no trusted
        apply link.
    """
    # ------------------------------------------------------------------
    # Gate 0 – Reject the whole record if the caller signals LLM origin.
    # ------------------------------------------------------------------
    if origin == "llm":
        logger.warning(
            "job_link_trust: rejected – origin=llm job_id=%s",
            job.get("job_id") or job.get("id") or "<unknown>",
        )
        return None

    # ------------------------------------------------------------------
    # Gate 1 – URL presence and scheme.
    # ------------------------------------------------------------------
    raw_url: Any = job.get(url_field) or job.get("alt_url") or job.get("source_url")
    if not raw_url or not isinstance(raw_url, str):
        return None
    url = raw_url.strip()
    if not url:
        return None
    scheme = url.split(":", 1)[0].lower()
    if scheme not in _ALLOWED_SCHEMES:
        logger.warning("job_link_trust: rejected – bad scheme '%s'", scheme)
        return None

    # ------------------------------------------------------------------
    # Gate 2 – Placeholder / fake URL patterns.
    # ------------------------------------------------------------------
    if is_placeholder_url(url):
        logger.warning("job_link_trust: rejected – placeholder url '%s'", url)
        return None

    # ------------------------------------------------------------------
    # Gate 3 – Sequential LinkedIn job ID (generated by LLM).
    # ------------------------------------------------------------------
    m = _SEQUENTIAL_LINKEDIN_JOB_ID_RE.search(url)
    if m:
        numeric_id = int(m.group("id"))
        if numeric_id < 10_000_000:  # real LinkedIn IDs are 10+ digits / > 10 M
            logger.warning(
                "job_link_trust: rejected – sequential LinkedIn job id %d in url '%s'",
                numeric_id,
                url,
            )
            return None

    # ------------------------------------------------------------------
    # Gate 4 – Trusted provenance in the job record.
    # A URL that passes all pattern checks is still untrusted unless the
    # record was written by the ingestion layer.
    # ------------------------------------------------------------------
    if not _has_trusted_provenance(job):
        logger.warning(
            "job_link_trust: rejected – no trusted provenance for url '%s' "
            "(job_id=%s, persisted_job_id=%s, source_job_id=%s, provider=%s, source_backed=%s)",
            url,
            job.get("job_id"),
            job.get("persisted_job_id"),
            job.get("source_job_id"),
            job.get("provider"),
            job.get("source_backed"),
        )
        return None

    logger.debug(
        "job_link_trust: accepted url '%s' for persisted_job_id=%s source_job_id=%s",
        url,
        job.get("persisted_job_id"),
        job.get("source_job_id"),
    )
    return url


def should_show_apply_button(job: dict[str, Any], *, origin: Optional[str] = None) -> bool:
    """Return True only if *job* has a trusted apply URL.

    Convenience wrapper for UI composers.
    """
    return resolve_trusted_apply_url(job, origin=origin) is not None


def safe_no_apply_link_message(job: dict[str, Any]) -> str:
    """Return a user-safe message when no trusted apply link is available.

    Never leaks internal error codes such as ``no_apply_link_available``.
    """
    title = job.get("title") or job.get("job_title") or "this job"
    company = job.get("company") or job.get("company_name") or ""
    label = f"{title} at {company}" if company else title
    return (
        f"I don't have a verified apply link for {label} yet. "
        "I can save it to your pipeline or help you search the company career page."
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _has_trusted_provenance(job: dict[str, Any]) -> bool:
    """Return True if the job record carries at least one trusted provenance marker.

    Trusted markers are fields that can ONLY be set by the backend ingestion
    layer or DB write path — never by LLM output or recent_context payload.

    +---------------------+----------------------------------------------+
    | Field               | Set by                                       |
    +=====================+==============================================+
    | persisted_job_id    | DB upsert in jobs_repo after source ingest   |
    | source_job_id       | Provider / scraper ingest (e.g. JSearch)     |
    | provider + bool     | Ingestion layer sets source_backed=True       |
    +---------------------+----------------------------------------------+

    ``job_id`` alone is NOT trusted: it can be synthesised by the LLM,
    copied from chat context, or inferred from ordinal references.
    """
    # Condition A: persisted by DB write path
    if job.get("persisted_job_id"):
        return True

    # Condition B: source identifier from provider / scraper
    if job.get("source_job_id"):
        return True

    # Condition C: provider-attributed AND explicitly marked as source-backed
    # Both fields must be present and truthy to prevent spoofing via LLM
    # payload that includes a fake ``provider`` string.
    provider = job.get("provider")
    source_backed = job.get("source_backed")
    if provider and source_backed is True:
        return True

    return False
