"""
src/services/pending_permissions.py

TTL-backed in-memory store for server-issued permission request IDs.

Prevents forged approval requests: the execute endpoint only processes a
permission_id that was generated by the server (via permission_factory),
belongs to the exact (user_id, action) pair, and has not expired or been
used already.

Architecture: in-memory dict with a threading lock — correct for the current
single-process Render deployment. Upgrade path: swap the backend for Redis
using the same register / validate_and_consume interface.
"""
from __future__ import annotations

import logging
import threading
import time

logger = logging.getLogger(__name__)

_TTL_SECONDS = 900  # 15 minutes — generous; most approvals happen within seconds
_store: dict[str, dict] = {}
_lock = threading.Lock()


def _prune() -> None:
    now = time.monotonic()
    expired = [k for k, v in _store.items() if v["expires_at"] < now]
    for k in expired:
        del _store[k]


def register(permission_id: str, user_id: str, action: str) -> None:
    """Record a server-issued permission ID. Called by permission_factory when building the request."""
    with _lock:
        _prune()
        _store[permission_id] = {
            "user_id": user_id,
            "action": action,
            "expires_at": time.monotonic() + _TTL_SECONDS,
        }
    logger.debug(
        "pending_permission: registered id=%s user=%s action=%s ttl=%ds",
        permission_id, user_id, action, _TTL_SECONDS,
    )


def validate_and_consume(permission_id: str, user_id: str, action: str) -> bool:
    """
    Validate and one-time-consume a permission ID.

    Returns True only when ALL of the following hold:
    - The id was issued by this server (not fabricated by the client)
    - It belongs to this exact user_id
    - It was issued for this exact action
    - It has not expired
    - It has not already been consumed

    Returns False (fail-closed) otherwise. The caller must raise 403.
    """
    with _lock:
        entry = _store.get(permission_id)
        if not entry:
            logger.warning(
                "pending_permission: unknown or already-consumed id=%s user=%s action=%s",
                permission_id, user_id, action,
            )
            return False
        if entry["user_id"] != user_id:
            logger.warning(
                "pending_permission: user mismatch id=%s expected=%s got=%s",
                permission_id, entry["user_id"], user_id,
            )
            return False
        if entry["action"] != action:
            logger.warning(
                "pending_permission: action mismatch id=%s expected=%s got=%s",
                permission_id, entry["action"], action,
            )
            return False
        if entry["expires_at"] < time.monotonic():
            del _store[permission_id]
            logger.warning(
                "pending_permission: expired id=%s user=%s action=%s",
                permission_id, user_id, action,
            )
            return False
        del _store[permission_id]  # one-time use: consumed on first valid validation
        logger.info(
            "pending_permission: consumed id=%s user=%s action=%s",
            permission_id, user_id, action,
        )
        return True


def pending_count() -> int:
    """Count live (unexpired) entries. Useful for testing and health checks."""
    now = time.monotonic()
    with _lock:
        return sum(1 for v in _store.values() if v["expires_at"] >= now)
