"""
Deleting a CV must actually remove its grounding (#1083).

Parsed-record model (DEC-20260716-002): Rico keeps parsed content, not the raw
file. Deleting the active/primary CV — including the synthetic 'profile-cv' card
— purges cv_text / cv_file_url / cv_structured and the profile.cv_filename /
profile.cv_extracted_at keys, so the deleted CV no longer grounds matching/chat
and cannot resurrect as an undeletable card. Structured profile facts are kept.

All DB / profile calls are mocked — no real database.
"""
from __future__ import annotations

import os
from types import SimpleNamespace
from unittest.mock import patch

import pytest

os.environ.setdefault("JWT_SECRET", "ricosecret" + "x" * 21)


@pytest.fixture(scope="module")
def auth_client():
    from fastapi.testclient import TestClient
    from src.api.app import app
    from src.api.auth import create_access_token

    token = create_access_token({"sub": "alice@rico.ai", "role": "user"})
    tc = TestClient(app, raise_server_exceptions=False)
    tc.cookies.set("access_token", token)
    return tc


def _primary_cv_doc():
    return {"id": "doc-cv-1", "doc_type": "cv", "is_primary": True, "filename": "cv.pdf"}


def _other_doc():
    return {"id": "doc-other-1", "doc_type": "other", "is_primary": False, "filename": "cert.pdf"}


class TestDeletePurgesCvGrounding:
    def test_delete_profile_cv_clears_grounding(self, auth_client):
        # Previously returned 400 (undeletable) — now the user can delete their
        # CV data and the grounding is purged.
        with patch("src.api.routers.files._db") as mock_db:
            mock_db.available = True
            mock_db.clear_cv_grounding.return_value = True
            r = auth_client.delete("/api/v1/user/files/profile-cv")
        assert r.status_code == 200
        assert r.json()["cleared_cv_grounding"] is True
        mock_db.clear_cv_grounding.assert_called_once_with("alice@rico.ai")
        mock_db.delete_user_document.assert_not_called()

    def test_delete_primary_cv_document_purges_grounding(self, auth_client):
        with patch("src.api.routers.files._db") as mock_db:
            mock_db.available = True
            mock_db.list_user_documents.return_value = [_primary_cv_doc(), _other_doc()]
            mock_db.delete_user_document.return_value = True
            mock_db.clear_cv_grounding.return_value = True
            r = auth_client.delete("/api/v1/user/files/doc-cv-1")
        assert r.status_code == 200
        assert r.json()["cleared_cv_grounding"] is True
        mock_db.clear_cv_grounding.assert_called_once_with("alice@rico.ai")

    def test_delete_other_document_does_not_purge_grounding(self, auth_client):
        with patch("src.api.routers.files._db") as mock_db:
            mock_db.available = True
            mock_db.list_user_documents.return_value = [_primary_cv_doc(), _other_doc()]
            mock_db.delete_user_document.return_value = True
            r = auth_client.delete("/api/v1/user/files/doc-other-1")
        assert r.status_code == 200
        assert r.json()["cleared_cv_grounding"] is False
        mock_db.clear_cv_grounding.assert_not_called()

    def test_delete_non_primary_cv_does_not_purge_active_grounding(self, auth_client):
        non_primary = dict(_primary_cv_doc(), id="doc-cv-2", is_primary=False)
        with patch("src.api.routers.files._db") as mock_db:
            mock_db.available = True
            mock_db.list_user_documents.return_value = [_primary_cv_doc(), non_primary]
            mock_db.delete_user_document.return_value = True
            r = auth_client.delete("/api/v1/user/files/doc-cv-2")
        assert r.status_code == 200
        assert r.json()["cleared_cv_grounding"] is False
        mock_db.clear_cv_grounding.assert_not_called()

    def test_delete_missing_document_still_404(self, auth_client):
        with patch("src.api.routers.files._db") as mock_db:
            mock_db.available = True
            mock_db.list_user_documents.return_value = []
            mock_db.delete_user_document.return_value = False
            r = auth_client.delete("/api/v1/user/files/nope")
        assert r.status_code == 404
        mock_db.clear_cv_grounding.assert_not_called()


class TestNoResurrectionAfterPurge:
    def test_build_profile_cv_record_none_when_filename_purged(self):
        # After clear_cv_grounding removes profile.cv_filename, the synthetic
        # 'profile-cv' card must not be regenerated by list_files.
        from src.api.routers import files as files_router

        purged = SimpleNamespace(
            cv_filename=None,
            cv_extracted_at=None,
            skills=[],
            years_experience=None,
            current_role=None,
        )
        with patch("src.api.routers.files.profile_repo.get_profile", return_value=purged):
            assert files_router.build_profile_cv_record("alice@rico.ai") is None
